[pytest]
# Укажи путь к файлу настроек твоего проекта (замени core.settings, если твоя главная папка называется иначе)
DJANGO_SETTINGS_MODULE = core.settings

pythonpath = . src

# В каких файлах искать тесты
python_files = tests.py test_*.py *_tests.py

# Дополнительные флаги: красивые цветные логи и отображение локальных переменных при ошибках
addopts = -v --showlocals

# Запрещаем предупреждениям замусоривать вывод консоли
filterwarnings =
    ignore::DeprecationWarning