# Generated by Django 5.0.6 on 2026-07-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_clicklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Product Image URL'),
        ),
    ]
