# Generated by Django 5.0.6 on 2026-07-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-internal_score', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='ali_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='AliExpress ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Commission Rate (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Internal Quality Score'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Old Price (USD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop ID'),
        ),
    ]
