# Generated by Django 5.0.6 on 2026-07-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Product Name'),
        ),
    ]
